networks:
  gamesdb:
volumes:
  gamesdb:
services:
  mongodb:
    image: mongo
    networks:
      gamesdb:
    volumes:
      - gamesdb:/data/db/:rw
  gamesdb:
    image: etna.spidererrol.co.uk:5050/tim-personal/coop-games
    networks:
      gamesdb:
    ports:
      - "3080:3000"
  mongo-express:
    image: mongo-express
    networks:
      gamesdb:
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
