networks:
  gamesdb:
volumes:
  gamesdb:
services:
  mongodb:
    image: mongo
    networks:
      gamesdb:
    volumes:
      - gamesdb:/data/db/:rw
  gamesdb:
    image: ghcr.io/spidererrol/gamesdb:main
    networks:
      gamesdb:
    ports:
      - "127.0.0.1:3080:3000"
    depends_on:
      - mongodb
  mongo-express:
    image: mongo-express
    networks:
      gamesdb:
    ports:
      - "127.0.0.1:8080:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
